### ISSUE TITLE
Kleuren in fase-link elementen

### ISSUE THREAD

**Issue by Robin1224** [Khdulkadir/the-startup-responsive-interactieve-website#4]
In de `fase-link` elementen staat grijze tekst. Wanneer je hier op hovert, wordt het element blauw en de titel tekst wit. 

Ik denk dat het zou helpen voor de leesbaarheid als de grijze tekst ook wit werd, omdat het contrast iets verloren gaat wanneer de kleur verandert.

Ook is er in het element van de design fase een zwart icoon rechtsboven in. Het zou helpen voor de leesbaarheid als ook dit icoon wit wordt bij de hover.

**Comment by Khdulkadir** [comment]
Fixed
